export const COMPANY_TYPES = [
  { value: "tecnologia", label: "Tecnología" },
  { value: "construccion", label: "Construcción" },
  { value: "salud", label: "Salud" },
  { value: "educacion", label: "Educación" },
  { value: "energia", label: "Energía" },
  { value: "logistica", label: "Logística" },
  { value: "consultoria", label: "Consultoría" },
  { value: "servicios", label: "Servicios" },
  { value: "mantenimiento", label: "Mantenimiento" },
  { value: "otro", label: "Otro" },
] as const;

export type CompanyType = (typeof COMPANY_TYPES)[number]["value"];

export const KEYWORD_PRESETS: Record<CompanyType, string[]> = {
  tecnologia: [
    "software",
    "sistema informático",
    "desarrollo web",
    "aplicación",
    "hardware",
    "red",
    "ciberseguridad",
    "nube",
    "datos",
    "TI",
    "tecnología",
    "soporte técnico",
  ],
  construccion: [
    "obra civil",
    "construcción",
    "infraestructura",
    "edificación",
    "carretera",
    "pavimentación",
    "refacción",
    "mantenimiento vial",
    "puente",
    "vivienda",
  ],
  salud: [
    "equipamiento médico",
    "medicamentos",
    "farmacéutico",
    "hospital",
    "clínica",
    "laboratorio",
    "insumos médicos",
    "ambulancia",
    "salud",
  ],
  educacion: [
    "material educativo",
    "mobiliario escolar",
    "capacitación",
    "formación",
    "escuela",
    "universidad",
    "libros",
    "equipamiento educativo",
    "laboratorio educativo",
  ],
  energia: [
    "energía solar",
    "paneles fotovoltaicos",
    "electricidad",
    "combustible",
    "gas",
    "generador",
    "subestación",
    "energía renovable",
    "iluminación",
  ],
  logistica: [
    "transporte",
    "logística",
    "distribución",
    "almacén",
    "flota vehicular",
    "flete",
    "carga",
    "mensajería",
    "courier",
  ],
  consultoria: [
    "consultoría",
    "asesoría",
    "auditoría",
    "estudio",
    "diagnóstico",
    "evaluación",
    "supervisión",
    "fiscalización",
    "gestión",
  ],
  servicios: [
    "servicios",
    "limpieza",
    "vigilancia",
    "seguridad",
    "catering",
    "alimentación",
    "eventos",
    "imprenta",
    "fotografía",
    "diseño",
    "jardinería",
    "fumigación",
  ],
  mantenimiento: [
    "mantenimiento",
    "mantenimiento preventivo",
    "mantenimiento correctivo",
    "reparación",
    "refacción",
    "instalación",
    "equipos",
    "maquinaria",
    "ascensor",
    "climatización",
    "plomería",
    "electricidad",
  ],
  otro: ["servicios", "bienes", "obras", "contratación"],
};
